### ISSUE TITLE
Return Code Class importJobDef

### ISSUE THREAD

**Issue by zoubairdjerbi** [enioka/jqm#191]
Incorrect return code when invocated class importJobDef in jqm/Main.java

 private static void importJobDef(String xmlpath)
{
try
{
EntityManager em = Helpers.getNewEm();
if (em.createQuery("SELECT q FROM Queue q WHERE q.defaultQueue = true").getResultList().size() != 1)
{
jqmlogger
.fatal("Cannot import a Job Definition when there are no queues defined. Create at least an engine first to create one");
em.close();
return;
}
String[] pathes = xmlpath.split(",");
for (String path : pathes)
{
XmlJobDefParser.parse(path, em);
}
em.close();
}
catch (Exception e)
{
jqmlogger.fatal("Could not import file", e);
return;
}
}

Example of Log from script execution "env_install_delivery_jqm.sh -n Sprint_222 -a PUA -e TEC1"

07/08 16:24:22.428|FATAL|main                                    |Main             |Could not import file
com.enioka.jqm.tools.JqmEngineException: an error occured while parsing the XML file. No changes were done to the configuration.
        at com.enioka.jqm.tools.XmlJobDefParser.parse(XmlJobDefParser.java:220)
        at com.enioka.jqm.tools.Main.importJobDef(Main.java:267)
        at com.enioka.jqm.tools.Main.main(Main.java:174)
Caused by: org.xml.sax.SAXParseException: cvc-complex-type.2.4.a: Invalid content was found starting with element 'filePath'. One of '{maxTimeRunning, application}' is expected.
        at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
        at org.apache.xerces.util.ErrorHandlerWrapper.error(Unknown Source)
        at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
        at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
        at org.apache.xerces.impl.xs.XMLSchemaValidator$XSIErrorReporter.reportError(Unknown Source)
        at org.apache.xerces.impl.xs.XMLSchemaValidator.reportSchemaError(Unknown Source)
        at org.apache.xerces.impl.xs.XMLSchemaValidator.handleStartElement(Unknown Source)
        at org.apache.xerces.impl.xs.XMLSchemaValidator.startElement(Unknown Source)
        at org.apache.xerces.jaxp.validation.DOMValidatorHelper.beginNode(Unknown Source)
        at org.apache.xerces.jaxp.validation.DOMValidatorHelper.validate(Unknown Source)
        at org.apache.xerces.jaxp.validation.DOMValidatorHelper.validate(Unknown Source)
        at org.apache.xerces.jaxp.validation.ValidatorImpl.validate(Unknown Source)
        at javax.xml.validation.Validator.validate(Unknown Source)
        at com.enioka.jqm.tools.XmlJobDefParser.parse(XmlJobDefParser.java:98)
        ... 2 more

**Comment by marcanpilami** [comment]
Thank you for the bug report. Indeed, return code is 0 even when XML import failed which is not a good behaviour.
We will check all CLI return codes as a consequence.

Marked for next maintenance release.
