### ISSUE TITLE
JQM with MySQL does not work as documented

### ISSUE THREAD

**Issue by schuettec** [enioka/jqm#220]
I do not really know if this is my fault or a bug in JQM, please let me know ;-)

First of all the error is an Exception related to transactions:
```
java -jar jqm.jar -createnode schuettec
13/07 11:04:12.008|INFO |main                                    |Main                                                                                                                                                                  |Creating engine node schuettec
13/07 11:04:13.979|INFO |main                                    |Helpers          |A default queue was created in                                                                                                                   the configuration
Exception in thread "main" com.enioka.jqm.tools.JqmRuntimeException: Could not create the engine
        at com.enioka.jqm.tools.Main.createEngine(Main.java:305)
        at com.enioka.jqm.tools.Main.main(Main.java:194)
Caused by: javax.persistence.RollbackException: Error while committing the transaction
        at org.hibernate.ejb.TransactionImpl.commit(TransactionImpl.java:92)
        at com.enioka.jqm.tools.Helpers.updateConfiguration(Helpers.java:558)
        at com.enioka.jqm.tools.Main.createEngine(Main.java:299)
        ... 1 more
Caused by: javax.persistence.OptimisticLockException: Row was updated or deleted by another transaction (or unsaved                                                                                                                  -value mapping was incorrect): [com.enioka.jqm.jpamodel.JndiObjectResourceParameter#1]
        at org.hibernate.ejb.AbstractEntityManagerImpl.wrapStaleStateException(AbstractEntityManagerImpl.java:1413)
        at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1329)
        at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1310)
        at org.hibernate.ejb.TransactionImpl.commit(TransactionImpl.java:80)
        ... 3 more
Caused by: org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-v                                                                                                                  alue mapping was incorrect): [com.enioka.jqm.jpamodel.JndiObjectResourceParameter#1]
        at org.hibernate.persister.entity.AbstractEntityPersister.check(AbstractEntityPersister.java:2521)
        at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:3240)
        at org.hibernate.persister.entity.AbstractEntityPersister.updateOrInsert(AbstractEntityPersister.java:3138)
        at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:3468)
        at org.hibernate.action.internal.EntityUpdateAction.execute(EntityUpdateAction.java:140)
        at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:395)
        at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:387)
        at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:304)
        at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListen                                                                                                                  er.java:349)
        at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:56)
        at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1195)
        at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:404)
        at org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction.beforeTransactionCommit(JdbcTransaction.j                                                                                                                  ava:101)
        at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.commit(AbstractTransactionImpl.java:175)
        at org.hibernate.ejb.TransactionImpl.commit(TransactionImpl.java:75)
        ... 3 more
```

My conf/resource.xml looks like this:
```
<?xml version="1.0" encoding="UTF-8"?>
<resources>	
	<resource 
	      name="jdbc/jqm"
          auth="Container"
          type="javax.sql.DataSource"
          factory="org.apache.tomcat.jdbc.pool.DataSourceFactory"
          testWhileIdle="true"
          testOnBorrow="false"
          testOnReturn="true"
          validationQuery="SELECT version()"
          validationInterval="1000"
          timeBetweenEvictionRunsMillis="60000"
          maxActive="100"
          minIdle="2"
          maxWait="30000"
          initialSize="5"
          removeAbandonedTimeout="3600"
          removeAbandoned="true"
          logAbandoned="true"
          minEvictableIdleTimeMillis="60000"
          jmxEnabled="true"
          username="jqm"
          password="jqm"
          driverClassName="com.mysql.jdbc.Driver"
          url="jdbc:mysql://localhost:3306/jqm"
          singleton="true"/> 
</resources>
```

In jqm.properties I removed the hibernate.dialect (because I think the documentation says that) - only comments are present in this file.

Just to be precise, here is my worklog showing everything I have done to configure everything:

JQM with MySQL worklog:
```
* Goto my.ini of MySQL Server and add the following in section [mysqld]
	init-file=jqm-mysql-init-script.sql
	general-log=1
	
* Create database
CREATE DATABASE jqm;

* Create JQM database user
CREATE USER 
    jqm IDENTIFIED BY 'jqm';

* Grant privileges
GRANT ALL PRIVILEGES ON jqm.* TO 'jqm'@'%';

* Check if that worked: 
SELECT host, user, password, authentication_string FROM user;

* If other credentials were used for the DB user, edit JQM/conf/resource.xml

* Reinitialize JQM
./jqm.sh createnode
```

What I get is the above exception plus a set of generated tables in MySQL so this makes me think there is a transaction bug in JQM:
```
+-----------------------------+
| Tables_in_jqm               |
+-----------------------------+
| deliverable                 |
| deploymentparameter         |
| globalparameter             |
| history                     |
| jndiobjectresource          |
| jndiobjectresourceparameter |
| jobdef                      |
| jobdefparameter             |
| jobinstance                 |
| message                     |
| node                        |
| pki                         |
| queue                       |
| rpermission                 |
| rrole                       |
| rrole_ruser                 |
| runtimeparameter            |
| ruser                       |
+-----------------------------+
```

And thats it. Can you tell me if I have done anything wrong?

Is this a bug in JQM?

**Comment by marcanpilami** [comment]
Thanks for the report. Sorry you are experiencing this. I'll try to reproduce and get back to you tomorrow.

**Comment by marcanpilami** [comment]
Hello,

this is indeed a bug. It is a regression caused by the new function allowing to "hot change" some options without server restart.

So you have two solutions. The first is to use the 1.3.7-SNAPSHOT release which contains a fix. Acceptable for tests. It is here:  [sonatype ossrh](https://oss.sonatype.org/service/local/repositories/snapshots/content/com/enioka/jqm/jqm-engine/1.3.7-SNAPSHOT/jqm-engine-1.3.7-20160714.103210-1.zip)

The other is a workaround, more acceptable for production environments, by running the following commands. They pre-create a resource. This prevents the engine from recreating it on node creation and skips the problematic code section.
```sql
use jqm
insert into JndiObjectResource(description, factory, lastModified, name, singleton, type) values('default parameters used to send e-mails', 'com.enioka.jqm.providers.MailSessionFactory', SYSDATE(), 'mail/default', 1, 'javax.mail.Session');
insert into JndiObjectResourceParameter (KEYNAME, lastModified, VALUE, resource_id) values('smtpServerHost', SYSDATE(), 'smtp.gmail.com', (select id from JndiObjectResource where name='mail/default'));
commit;
```

Does any of these answers work for you? And thanks a lot for the great bug report - we do not often see such precision.

Marc-Antoine

**Comment by schuettec** [comment]
Thanks a lot for the quick answer! JQM is up and running!

I downloaded the 1.3.7-SNAPSHOT like you suggested. I will continue my
tests with this version. Currently we are not in productive state so this
will fit our needs. For a productive installation I would gladly wait for
your next release.

By the way I like your idea of integrating maven to get the job
deployments! Great!

2016-07-14 12:43 GMT+02:00 marcanpilami <notifications@github.com>:

**Comment by marcanpilami** [comment]
You are welcome. Glad you've got it running. The Maven thing came as a funny bonus at the end of a  sprint one day when we realized how little time devs had for packaging... 

And well, if you have any suggestions, do not hesitate to open tickets - as a new dev cycle is just beginning, it is a very good time to do so!

**Comment by schuettec** [comment]
Glad to hear. This would be a great time-saving, developer- and
admin-friendly feature ;-) On a cluster it would be comfortable to only
specify a string in the database and get everything up an running.

Am 15.07.2016 11:09 vorm. schrieb "marcanpilami" <notifications@github.com>:
