### ISSUE TITLE
Bug :  DeliverableTest.testGetOneDeliverableWithAuthWithSsl fails on Mac OS

### ISSUE THREAD

**Issue by Pauleing** [enioka/jqm#223]
DeliverableTest.testGetOneDeliverableWithAuthWithSsl fails on Mac OS.

Output : 

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
objc[13778]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre/bin/java and /Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
Running com.enioka.jqm.tools.DeliverableTest
[Server@3c9168dc]: [Thread[main,5,main]]: checkRunning(false) entered
[Server@3c9168dc]: [Thread[main,5,main]]: checkRunning(false) exited
[Server@3c9168dc]: [Thread[main,5,main]]: setDatabaseName(0,testdbengine)
[Server@3c9168dc]: [Thread[main,5,main]]: checkRunning(false) entered
[Server@3c9168dc]: [Thread[main,5,main]]: checkRunning(false) exited
[Server@3c9168dc]: [Thread[main,5,main]]: setDatabasePath(0,mem:testdbengine)
26/07 10:25:22.639|DEBUG|main                                    |JqmBaseTest      |**********************************************************
26/07 10:25:22.641|DEBUG|main                                    |JqmBaseTest      |Starting test testGetOneDeliverableWithAuthWithSsl
26/07 10:25:22.642|INFO |main                                    |JndiContext      |Resetting singleton JNDI resource cache
26/07 10:25:28.200|INFO |JQM engine;;localhost                   |JqmEngine        |JQM engine version 1.4.1-SNAPSHOT for node localhost is starting
26/07 10:25:28.200|INFO |JQM engine;;localhost                   |JqmEngine        |Java version is 1.8.0_20. JVM was made by Oracle Corporation as Java HotSpot(TM) 64-Bit Server VM version 25.20-b23
26/07 10:25:28.267|INFO |JQM engine;;localhost                   |Helpers          |Setting general log level at DEBUG which translates as log4j level DEBUG
26/07 10:25:28.274|INFO |JQM engine;;localhost                   |JqmEngine        |JMX remote listener will not be started as JMX registry port and JMX server port parameters are not both defined
26/07 10:25:28.325|INFO |JQM engine;;localhost                   |JettyServer      |JQM will use SSL for all HTTP communications as parameter enableWsApiSsl is 'true'
26/07 10:25:28.325|INFO |JQM engine;;localhost                   |JettyServer      |JQM will use its internal PKI for all certificates as parameter enableInternalPki is 'true'
26/07 10:25:33.169|DEBUG|JQM engine;;localhost                   |JettyServer      |Jetty will bind on 192.168.0.73:0
26/07 10:25:33.171|INFO |JQM engine;;localhost                   |JettyServer      |Jetty will now load the web service application war
26/07 10:25:36.483|INFO |JQM engine;;localhost                   |tainerInitializer|Registering the Jersey servlet application, named com.enioka.jqm.api.JqmRestApp, at the servlet mapping /ws/*, with the Application class of the same name.
26/07 10:25:36.659|INFO |JQM engine;;localhost                   |JqmWebServices   |Initializing Shiro environment
26/07 10:25:36.661|INFO |JQM engine;;localhost                   |EnvironmentLoader|Starting Shiro environment initialization.
26/07 10:25:37.012|INFO |JQM engine;;localhost                   |ityManagerFactory|Realms have been explicitly set on the SecurityManager instance - auto-setting of realms will not occur.
26/07 10:25:37.022|INFO |JQM engine;;localhost                   |EnvironmentLoader|Shiro environment initialized in 360 ms.
26/07 10:25:37.056|DEBUG|JQM engine;;localhost                   |HibernateClient  |Creating connection pool to database
26/07 10:25:37.992|INFO |JQM engine;;localhost                   |pplicationHandler|Initiating Jersey application, version Jersey: 2.6 2014-02-18 21:52:53...
26/07 10:25:38.771|INFO |JQM engine;;localhost                   |JettyServer      |Jetty has started on port 60449
26/07 10:25:38.772|INFO |JQM engine;;localhost                   |JqmEngine        |JMX management beans will not be loaded as JMX server port is null or zero
26/07 10:25:38.797|INFO |JQM engine;;localhost

|JqmEngine        |Security manager was registered
26/07 10:25:38.876|INFO |JQM engine;;localhost                   |QueuePoller      |Engine localhost will poll JobInstances on queue VIPQueue every 0s with 40 threads for concurrent instances
26/07 10:25:38.878|INFO |JQM engine;;localhost                   |QueuePoller      |Engine localhost will poll JobInstances on queue NormalQueue every 0s with 2 threads for concurrent instances
26/07 10:25:38.885|INFO |JQM engine;;localhost                   |QueuePoller      |Engine localhost will poll JobInstances on queue SlowQueue every 1s with 1 threads for concurrent instances
26/07 10:25:38.889|INFO |JQM engine;;localhost                   |JqmEngine        |All required queues are now polled
26/07 10:25:39.001|INFO |INTERNAL_POLLER;polling orders;         |InternalPoller   |Start of the internal poller
26/07 10:25:39.005|INFO |JQM engine;;localhost                   |JqmEngine        |End of JQM engine initialization
26/07 10:25:39.048|DEBUG|JQM engine;;localhost                   |HibernateClient  |Creating connection pool to database
26/07 10:25:39.468|DEBUG|TestJqmApplication;payload;1            |Loader           |A loader/runner thread has just started for Job Instance 1. Jar is: jqm-tests/jqm-test-pyl/target/test.jar - class is: pyl.EngineApiSendDeliverable
26/07 10:25:39.470|DEBUG|TestJqmApplication;payload;1            |LibraryCache     |Resolving classpath for job definition TestJqmApplication
26/07 10:25:41.791|DEBUG|TestJqmApplication;payload;1            |JarClassLoader   |Will now load class: pyl.EngineApiSendDeliverable
FILENAME: jqm-test-deliverable4.txt
26/07 10:25:41.941|DEBUG|TestJqmApplication;payload;1            |JobManagerHandler|A deliverable is added. Stored as target/outputfiles/TestJqmApplication/1/7e28d519-e23b-448c-a9de-6235e79598c3.txt. Initial name: jqm-test-deliverable4.txt
26/07 10:25:41.992|DEBUG|TestJqmApplication;payload;1            |Loader           |End of loader for JobInstance 1. Thread will now end
26/07 10:25:42.054|DEBUG|JQM engine;;localhost                   |SimpleApiSecurity|The client API will use authentication to download files
26/07 10:25:42.054|DEBUG|JQM engine;;localhost                   |SimpleApiSecurity|The client API will create an internal secret to access the simple API for file downloading
26/07 10:25:43.236|DEBUG|JQM engine;;localhost                   |JqmBaseTest      |*** Cleaning after test testGetOneDeliverableWithAuthWithSsl
26/07 10:25:43.238|INFO |JQM engine;;localhost                   |JqmEngine        |JQM engine localhost has received a stop order
26/07 10:25:43.239|INFO |JQM engine;;localhost                   |QueuePoller      |Poller has received a stop order
26/07 10:25:43.239|INFO |JQM engine;;localhost                   |QueuePoller      |Poller has received a stop order
26/07 10:25:43.240|INFO |JQM engine;;localhost                   |QueuePoller      |Poller has received a stop order
26/07 10:25:43.240|INFO |QUEUE_POLLER;polling;NormalQueue        |QueuePoller      |Poller loop on queue NormalQueue is stopping [engine localhost]
26/07 10:25:43.240|INFO |QUEUE_POLLER;polling;NormalQueue        |QueuePoller      |Poller on queue NormalQueue has ended normally
26/07 10:25:43.240|INFO |QUEUE_POLLER;polling;VIPQueue           |QueuePoller      |Poller loop on queue VIPQueue is stopping [engine localhost]
26/07 10:25:43.240|INFO |QUEUE_POLLER;polling;SlowQueue          |QueuePoller      |Poller loop on queue SlowQueue is stopping [engine localhost]
26/07 10:25:43.241|INFO |QUEUE_POLLER;polling;SlowQueue          |QueuePoller      |Poller on queue SlowQueue has ended normally
26/07 10:25:43.241|INFO |QUEUE_POLLER;polling;VIPQueue           |QueuePoller      |Poller on queue VIPQueue has ended normally
26/07 10:25:43.258|DEBUG|QUEUE_POLLER;polling;VIPQueue           |Ctx              |Cleaning after Hibernate during WS application shutdown
26/07 10:25:43.264|INFO |QUEUE_POLLER;polling;VIPQueue           |JqmWebServices   |Cleaning up Shiro Environment
26/07 10:25:43.372|INFO |QUEUE_POLLER;poll

ing;VIPQueue           |JettyServer      |Jetty has stopped
26/07 10:25:43.372|INFO |QUEUE_POLLER;polling;VIPQueue           |InternalPoller   |Internal poller has received a stop request
26/07 10:25:43.373|INFO |INTERNAL_POLLER;polling orders;         |InternalPoller   |End of the internal poller
26/07 10:25:43.377|INFO |QUEUE_POLLER;polling;VIPQueue           |JqmEngine        |JQM engine has stopped
26/07 10:25:43.378|DEBUG|JQM engine;;localhost                   |JqmEngine        |Stop order was correctly handled. Engine for node localhost has stopped.
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 22.813 sec <<< FAILURE! - in com.enioka.jqm.tools.DeliverableTest
testGetOneDeliverableWithAuthWithSsl(com.enioka.jqm.tools.DeliverableTest)  Time elapsed: 21.265 sec  <<< ERROR!
com.enioka.jqm.api.JqmClientException: Could not create a webserver-local copy of the file. The remote node may be down.
	at com.enioka.jqm.api.HibernateClient.getFile(HibernateClient.java:1795)
	at com.enioka.jqm.api.HibernateClient.getDeliverableContent(HibernateClient.java:1649)
	at com.enioka.jqm.api.HibernateClient.getDeliverableContent(HibernateClient.java:1563)
	at com.enioka.jqm.api.HibernateClient.getDeliverableContent(HibernateClient.java:1540)
	at com.enioka.jqm.tools.DeliverableTest.testGetOneDeliverableWithAuthWithSsl(DeliverableTest.java:143)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: javax.net.ssl.SSLPeerUnverifiedException: Host name 'MacBook-Pro-de-Paulin.local' does not match the certificate subject provided by the peer (CN=MacBook-Pro-de-Paulin.local)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.verifyHostname(SSLConnectionSocketFactory.java:465)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:395)
	at org.apache.http.conn.ssl.SSLConnectionSocket

Factory.connectSocket(SSLConnectionSocketFactory.java:353)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at com.enioka.jqm.api.HibernateClient.getFile(HibernateClient.java:1769)
	... 33 more

**Comment by marcanpilami** [comment]
@Pauleing should be fixed now. Could you please check on your Mac?

**Comment by Pauleing** [comment]
@marcanpilami The error still occurs
