### ISSUE TITLE
java.lang.NullPointerException while calling JobManager.jobInstanceID()

### ISSUE THREAD

**Issue by anissofiane** [enioka/jqm#245]
After a parent job launch and wait for childs jobs there is a java.lang.NullPointerException while calling JobManager.jobInstanceID().
All the jobs are configured whith the same specificIsolationContext.

Stack trace :
java.lang.NullPointerException
	at com.enioka.jqm.tools.JobManagerHandler.invoke(JobManagerHandler.java:114)
	at com.sun.proxy.$Proxy63.jobInstanceID(Unknown Source)
	at es.alerce.geodis.base.BaseRunJob.getJobInstanceId(BaseRunJob.java:45)
	at es.alerce.geodis.base.BaseConnectionRunJob.insertarErrorEnLogInterfaz(BaseConnectionRunJob.java:84)
	at es.alerce.geodis.base.BaseConnectionRunJob.startJob(BaseConnectionRunJob.java:58)
	at es.alerce.geodis.base.BaseRunJob.run(BaseRunJob.java:39)
	at com.enioka.jqm.tools.JarClassLoader.launchRunnable(JarClassLoader.java:234)
	at com.enioka.jqm.tools.JarClassLoader.launchJar(JarClassLoader.java:131)
	at com.enioka.jqm.tools.Loader.runPayload(Loader.java:222)
	at com.enioka.jqm.tools.Loader.run(Loader.java:103)
	at java.lang.Thread.run(Thread.java:701)

**Comment by marcanpilami** [comment]
Hi, I suspect you are using a static field for storing your JobManager - since you are sharing the isolation context, it means static variables are shared! Could you please show us the code of es.alerce.geodis.base.BaseRunJob.getJobInstanceId(BaseRunJob.java:45) to check this?

**Comment by anissofiane** [comment]
You're right Alerce uses a JobManager as a static field.

private static JobManager jm;

**Comment by marcanpilami** [comment]
OK. Keeping this ticket open : we shall add a warning if an injection is done on a static field when using a shared classloader
