### ISSUE TITLE
Sporadic NullPointerException on JobManager.enqueue()

### ISSUE THREAD

**Issue by jcdugas** [enioka/jqm#283]
In production job, sporadic issue (couples in a month) when launching a new job at the end of a job, with JobManager.enqueue() method.

```
Caused by: java.lang.NullPointerException
	at com.enioka.jqm.tools.JobManagerHandler.shouldKill(JobManagerHandler.java:252)
	at com.enioka.jqm.tools.JobManagerHandler.invoke(JobManagerHandler.java:100)
	at com.sun.proxy.$Proxy607.enqueue(Unknown Source)
	at es.alerce.geodis.dao.InterfacesDao.launchJQM(InterfacesDao.java:195)
```

Job definition of the 2 jobs has been checked and is complete, so it's not a declaration/configuration issue.

Checking source code, it seems that jobInstance is null in JobManagerHandler on line 252, so em.find() on preceding line is not working, at all time, or maybe that this.ji.getId() is null.

I think that em.find() return value should be tested for nullity before proceeding, to increase code robustness.

InterfacesDao.java:195
`jm.enqueue(jqmName, "TEOS", null, null, null, null, null, null, null, new HashMap<String, String>());`

**Comment by marcanpilami** [comment]
This would mean the current job instance does not exist, which is (of course) seemingly impossible since this method can only be called from a running job instance... As fetching the current JI is used pretty much everywhere, if this object cannot be found the JI will crash in all cases, not only on calls to this API. Is it always the same log? And what is sporadic?

**Comment by jcdugas** [comment]
Only two errors, in all. First job execution does'nt have it's log file, second one has. So no other stacktrace to compare with...

**Comment by marcanpilami** [comment]
Closing for lack of activity.
