### ISSUE TITLE
JQM with MariaDB: Queue poller has failed! It will stop.

### ISSUE THREAD

**Issue by echipachenko** [enioka/jqm#297]
Hi!
We try to use MariaDB (mysql fork) database, and issue was occurred.
JQM Engine is not started, and go to stop.

```
17/10 11:45:36.792|ERROR|QUEUE_POLLER;polling;CTCBATCH           |QueuePoller      |Queue poller has failed! It will stop.
com.enioka.jqm.jdbc.DatabaseException: UPDATE JOB_INSTANCE j1 FORCE INDEX (`PRIMARY`) RIGHT JOIN (SELECT j3.ID FROM JOB_INSTANCE j3 FORCE INDEX(`IDX_JOB_INSTANCE_1`) WHERE j3.STATUS = 'SUBMITTED' AND j3.QUEUE = ? AND (j3.HIGHLANDER = FALSE OR (j3.HIGHLANDER = TRUE AND (SELECT COUNT(1) FROM JOB_INSTANCE j4 FORCE INDEX(`IDX_JOB_INSTANCE_2`) WHERE j4.STATUS IN ('ATTRIBUTED' , 'RUNNING') AND j4.JOBDEF = j3.JOBDEF) = 0)) ORDER BY PRIORITY DESC, INTERNAL_POSITION FOR UPDATE LIMIT ?) j2 ON j2.ID = j1.ID SET j1.NODE = ?, j1.STATUS = 'ATTRIBUTED', j1.DATE_ATTRIBUTION = CURRENT_TIMESTAMP(3)
	at com.enioka.jqm.jdbc.DbConn.runUpdate(DbConn.java:123)
	at com.enioka.jqm.tools.QueuePoller.dequeue(QueuePoller.java:174)
	at com.enioka.jqm.tools.QueuePoller.run(QueuePoller.java:226)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLSyntaxErrorException: (conn=822) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'LIMIT 1) j2 ON j2.ID = j1.ID SET j1.NODE = 50, j1.STATUS = 'ATTRIBUTED', j1.DATE' at line 1
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:158)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:118)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:235)
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:224)
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.execute(MariaDbPreparedStatementClient.java:159)
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeUpdate(MariaDbPreparedStatementClient.java:192)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:138)
	at com.sun.proxy.$Proxy3.executeUpdate(Unknown Source)
	at com.enioka.jqm.jdbc.DbConn.runUpdate(DbConn.java:102)
	... 3 more
Caused by: java.sql.SQLException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'LIMIT 1) j2 ON j2.ID = j1.ID SET j1.NODE = 50, j1.STATUS = 'ATTRIBUTED', j1.DATE' at line 1
Query is: UPDATE JOB_INSTANCE j1 FORCE INDEX (`PRIMARY`) RIGHT JOIN (SELECT j3.ID FROM JOB_INSTANCE j3 FORCE INDEX(`IDX_JOB_INSTANCE_1`) WHERE j3.STATUS = 'SUBMITTED' AND j3.QUEUE = ? AND (j3.HIGHLANDER = FALSE OR (j3.HIGHLANDER = TRUE AND (SELECT COUNT(1) FROM JOB_INSTANCE j4 FORCE INDEX(`IDX_JOB_INSTANCE_2`) WHERE j4.STATUS IN ('ATTRIBUTED' , 'RUNNING') AND j4.JOBDEF = j3.JOBDEF) = 0)) ORDER BY PRIORITY DESC, INTERNAL_POSITION FOR UPDATE LIMIT ?) j2 ON j2.ID = j1.ID SET j1.NODE = ?, j1.STATUS = 'ATTRIBUTED', j1.DATE_ATTRIBUTION = CURRENT_TIMESTAMP(3), parameters [310,1,50]
	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:146)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:217)
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:218)
	... 12 more

```

**Comment by marcanpilami** [comment]
Will be included in the 2.1.0 release. Already present in 2.1.0-SNAPSHOT build on OSSRH if you want.
