### ISSUE TITLE
Jobs stuck in "running" state when using the discrete resource manager

### ISSUE THREAD

**Issue by tuxella** [enioka/jqm#336]
16/11 15:29:24.045|ERROR|DIV;payload;10472                       |unningJobInstance|An error occurred while finalizing the job instance.
java.lang.NullPointerException
	at com.enioka.jqm.tools.DiscreteResourceManager.releaseResource(DiscreteResourceManager.java:164)
	at com.enioka.jqm.tools.QueuePoller.releaseResources(QueuePoller.java:416)
	at com.enioka.jqm.tools.RunningJobInstanceManager.signalEndOfRun(RunningJobInstanceManager.java:52)
	at com.enioka.jqm.tools.RunningJobInstance.endOfRun(RunningJobInstance.java:233)
	at com.enioka.jqm.tools.RunningJobInstance.actualRun(RunningJobInstance.java:189)
	at com.enioka.jqm.tools.RunningJobInstance.run(RunningJobInstance.java:85)
	at java.lang.Thread.run(Thread.java:745)

**Comment by tuxella** [comment]
Same with 
```
$ java -version
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)
```

Stacktrace:
```19/11 13:02:11.338|ERROR|DIV;payload;2800                        |tyResourceManager|TOKEN : com.enioka.jqm.tools.DiscreteResourceManager$Token@14354b3d
19/11 13:02:11.339|ERROR|DIV;payload;2800                        |tyResourceManager|TOKEN FREE true
19/11 13:02:11.340|ERROR|DIV;payload;2800                        |unningJobInstance|An error occurred while finalizing the job instance.
com.enioka.jqm.tools.JqmRuntimeException: some NPE where there should be none
	at com.enioka.jqm.tools.DiscreteResourceManager.releaseResource(DiscreteResourceManager.java:185)
	at com.enioka.jqm.tools.QueuePoller.releaseResources(QueuePoller.java:416)
	at com.enioka.jqm.tools.RunningJobInstanceManager.signalEndOfRun(RunningJobInstanceManager.java:52)
	at com.enioka.jqm.tools.RunningJobInstance.endOfRun(RunningJobInstance.java:235)
	at com.enioka.jqm.tools.RunningJobInstance.actualRun(RunningJobInstance.java:191)
	at com.enioka.jqm.tools.RunningJobInstance.run(RunningJobInstance.java:85)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at com.enioka.jqm.tools.DiscreteResourceManager.releaseResource(DiscreteResourceManager.java:173)
	... 6 more
```
