### ISSUE TITLE
DB field too long, cause java.sql.SQLSyntaxErrorException

### ISSUE THREAD

**Issue by croooo** [enioka/jqm#367]
JQM version : 3.0.0
Database : mariaDB 10.1.38 on Debian 9 (default server charset is utf8mb4)
```

31/07 10:11:18.968|INFO |main                                    |Db               |Running migration script /sql/00000_00001.sql
Exception in thread "main" com.enioka.jqm.jdbc.DatabaseException: 
CREATE TABLE DELIVERABLE
(
        ID INTEGER NOT NULL,
        FILE_FAMILY VARCHAR(100),
        PATH VARCHAR(1024),
        JOB_INSTANCE INTEGER NOT NULL, /* Not an FK, as this is used by both Hostory and JobDef */
        ORIGINAL_FILE_NAME VARCHAR(1024),
        RANDOM_ID VARCHAR(200) NOT NULL,

        CONSTRAINT PK_DELIVERABLE PRIMARY KEY(ID),
        CONSTRAINT UK_DELIVERABLE UNIQUE(RANDOM_ID)
)
        at com.enioka.jqm.jdbc.DbConn.runRawUpdate(DbConn.java:154)
        at com.enioka.jqm.jdbc.ScriptRunner.run(ScriptRunner.java:51)
        at com.enioka.jqm.jdbc.Db.dbUpgrade(Db.java:419)
        at com.enioka.jqm.jdbc.Db.init(Db.java:271)
        at com.enioka.jqm.jdbc.Db.<init😠Db.java:159)
        at com.enioka.jqm.tools.CommandUpdateSchema.doWork(CommandUpdateSchema.java:21)
        at com.enioka.jqm.tools.Main.runCommand(Main.java:123)
        at com.enioka.jqm.tools.Main.main(Main.java:76)
Caused by: java.sql.SQLSyntaxErrorException: (conn=47) Specified key was too long; max key length is 767 bytes
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:242)

```

**Comment by marcanpilami** [comment]
Damn 4-bytes encodings.

Well, this field is only used we UUID string representation, so about 36 characters. 200 is overkill, reducing to 100 is OK including for future evolutions.
