### ISSUE TITLE
Exception at launching job with module parameter of payload empty

### ISSUE THREAD

**Issue by deiv** [enioka/jqm#383]
If I create a payload without filling the module, launching it, gives the next exception:

```java
21/01 16:53:11.657|INFO |job definition 5;payload;85             |unningJobInstance|Job instance 85 has crashed. Exception was:
java.lang.NullPointerException
	at java.lang.ProcessEnvironment.validateValue(ProcessEnvironment.java:120)
	at java.lang.ProcessEnvironment.access$400(ProcessEnvironment.java:61)
	at java.lang.ProcessEnvironment$Value.valueOf(ProcessEnvironment.java:203)
	at java.lang.ProcessEnvironment$StringEnvironment.put(ProcessEnvironment.java:243)
	at java.lang.ProcessEnvironment$StringEnvironment.put(ProcessEnvironment.java:221)
	at java.util.AbstractMap.putAll(AbstractMap.java:281)
	at com.enioka.jqm.tools.ShellJobInstanceTracker.run(ShellJobInstanceTracker.java:122)
	at com.enioka.jqm.tools.RunningJobInstance.actualRun(RunningJobInstance.java:180)
	at com.enioka.jqm.tools.RunningJobInstance.run(RunningJobInstance.java:85)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by marcanpilami** [comment]
Indeed, line https://github.com/enioka/jqm/blob/jqm-all-2.2.2/jqm-all/jqm-runner/jqm-runner-shell/src/main/java/com/enioka/jqm/tools/ShellJobInstanceTracker.java#L97 is wrong. Thanks for reporting! This will be in the next maintenance release.
