### ISSUE TITLE
JQM Spring context, Spring Boot compatibility 

### ISSUE THREAD

**Issue by simonwibberley** [enioka/jqm#389]
Is the Spring context when generated by JQM compatible with Spring Boot? https://jqm.readthedocs.io/en/jqm-all-2.2.1/jobs/spring.html#by-having-jqm-set-the-context

If so, how to I register various auto configurations to the JQM generated context? 

Thanks!

**Comment by marcanpilami** [comment]
Actually, all our samples (links inside the doc) use Spring Boot so the answer is yes, the `com.enioka.jqm.runner.spring.AnnotationSpringRunner` job runner is compatible with Spring Boot. If you have multiple independent `@Configuration` beans and want to have them all inside the persistent Spring context, just use the `additionalScan` parameter to specify the namespaces to scan on context refresh.

**Comment by simonwibberley** [comment]
Hi Marc, thanks for the reply. I may have expressed my issue incorrectly: I'm trying to load an autoconfigured spring boot application, additionally, I need to _disable_ some of the autoconfiguration. My 'vanilla' spring app is :

```
@EnableAutoConfiguration(exclude={DisableOne.class,DisableTwo.class})
// We need the special object mapper, though.
@Import({MoreConfig.class})
@ComponentScan(basePackages={"some.dao.classes"})
public class CLIRunner implements CommandLineRunner {
```

I'm having trouble figuring out how to apply the above to the JQM gernerated context, do I simple add those annotations to a @Configuration class and add that to the scan?

Thanks!

**Comment by simonwibberley** [comment]
I this a `@Configuraiton` class in the package scan path:
```
@Configuration
@EnableAutoConfiguration(exclude={HibernateJpaAutoConfiguration.class, CamundaBpmAutoConfiguration.class, CamundaBpmRestJerseyAutoConfiguration.class, ValidationAutoConfiguration.class})
@Import({ObjectMapperConfiguration.class})
public class SpringCrawlerConfiguration {

}
```
And got the following error:
```
06/03 14:37:13.757|INFO |JQMSpringCollector;payload;30830        |lassloaderManager|Using an existing specific isolation context : MainSharedSpringContext
06/03 14:37:13.758|INFO |JQMSpringCollector;payload;30830        |LibraryResolverFS|The cache for application JQMSpringCollector will be reloaded
14:37:14.581 [JQMSpringCollector;payload;30830] DEBUG org.springframework.context.annotation.ClassPathBeanDefinitionScanner - Identified candidate component class: URL [jar:file:/home/sw206/git/springcrawler/target/acled-spring-crawler-1.3.5-SNAPSHOT.jar!/com/casm/acled/crawler/spring/jqm/JQMRunner.class]
14:37:14.581 [JQMSpringCollector;payload;30830] DEBUG org.springframework.context.annotation.ClassPathBeanDefinitionScanner - Ignored because not a concrete top-level class: URL [jar:file:/home/sw206/git/springcrawler/target/acled-spring-crawler-1.3.5-SNAPSHOT.jar!/com/casm/acled/crawler/spring/service/CrawlerService$ShutdownConfig.class]
14:37:14.581 [JQMSpringCollector;payload;30830] DEBUG org.springframework.context.annotation.ClassPathBeanDefinitionScanner - Identified candidate component class: URL [jar:file:/home/sw206/git/springcrawler/target/acled-spring-crawler-1.3.5-SNAPSHOT.jar!/com/casm/acled/crawler/spring/service/CrawlerService.class]
14:37:14.581 [JQMSpringCollector;payload;30830] DEBUG org.springframework.context.annotation.ClassPathBeanDefinitionScanner - Ignored because not a concrete top-level class: URL [jar:file:/home/sw206/git/springcrawler/target/acled-spring-crawler-1.3.5-SNAPSHOT.jar!/com/casm/acled/crawler/spring/cli/CLIRunner$ShutdownConfig.class]
14:37:14.582 [JQMSpringCollector;payload;30830] DEBUG org.springframework.context.annotation.ClassPathBeanDefinitionScanner - Identified candidate component class: URL [jar:file:/home/sw206/git/springcrawler/target/acled-spring-crawler-1.3.5-SNAPSHOT.jar!/com/casm/acled/crawler/spring/SpringCrawlerConfiguration.class]
14:37:14.582 [JQMSpringCollector;payload;30830] DEBUG org.springframework.context.annotation.ClassPathBeanDefinitionScanner - Identified candidate component class: URL [jar:file:/home/sw206/git/springcrawler/target/acled-spring-crawler-1.3.5-SNAPSHOT.jar!/com/casm/acled/crawler/spring/config/SpringCrawlerConfiguration.class]
06/03 14:37:14.582|INFO |JQMSpringCollector;payload;30830        |obInstanceTracker|Job instance 30830 has crashed. Exception was:
com.enioka.jqm.api.JobRunnerException: event handler could not be loaded or run: com.enioka.jqm.handler.AnnotationSpringContextBootstrapHandler
	at com.enioka.jqm.tools.PayloadClassLoader.launchJar(PayloadClassLoader.java:207)
	at com.enioka.jqm.tools.JavaJobInstanceTracker.run(JavaJobInstanceTracker.java:127)
	at com.enioka.jqm.tools.RunningJobInstance.actualRun(RunningJobInstance.java:180)
	at com.enioka.jqm.tools.RunningJobInstance.run(RunningJobInstance.java:85)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.enioka.jqm.tools.PayloadClassLoader.launchJar(PayloadClassLoader.java:203)
	... 4 more
Caused by: org.springframework.context.annotation.ConflictingBeanDefinitionException: Annotation-specified bean name 'springCrawlerConfiguration' for bean class [com.casm.acled.crawler.spring.config.SpringCrawlerConfiguration] conflicts with existing, non-compatible bean definition of same name and class [com.casm.acled.crawler.spring.SpringCrawlerConfiguration]
	at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.checkCandidate(ClassPathBeanDefinitionScanner.java:348)
	at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.doScan(ClassPathBeanDefinitionScanner.java:286)
	at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.scan(ClassPathBeanDefinitionScanner.java:253)
	at org.springframework.context.annotation.AnnotationConfigApplicationContext.scan(AnnotationConfigApplicationContext.java:170)
	at com.enioka.jqm.handler.AnnotationSpringContextBootstrapHandler.run(AnnotationSpringContextBootstrapHandler.java:124)
	... 9 more
```

Any ideas? 

Many thanks,

**Comment by simonwibberley** [comment]
Changing the name of the config class worked, although I can't find any conflicts in the source code...

I'm now on to this error about multiple refreshes:

```
 |JQMSpringCollector;payload;30856        |obInstanceTracker|Job instance 30856 has crashed. Exception was:
com.enioka.jqm.api.JobRunnerException: event handler could not be loaded or run: com.enioka.jqm.handler.AnnotationSpringContextBootstrapHandler
	at com.enioka.jqm.tools.PayloadClassLoader.launchJar(PayloadClassLoader.java:207)
	at com.enioka.jqm.tools.JavaJobInstanceTracker.run(JavaJobInstanceTracker.java:127)
	at com.enioka.jqm.tools.RunningJobInstance.actualRun(RunningJobInstance.java:180)
	at com.enioka.jqm.tools.RunningJobInstance.run(RunningJobInstance.java:85)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.enioka.jqm.tools.PayloadClassLoader.launchJar(PayloadClassLoader.java:203)
	... 4 more
Caused by: java.lang.IllegalStateException: GenericApplicationContext does not support multiple refresh attempts: just call 'refresh' once
	at org.springframework.context.support.GenericApplicationContext.refreshBeanFactory(GenericApplicationContext.java:266)
	at org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory(AbstractApplicationContext.java:636)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:521)
	at com.enioka.jqm.handler.AnnotationSpringContextBootstrapHandler.run(AnnotationSpringContextBootstrapHandler.java:153)
	... 9 more
```

**Comment by simonwibberley** [comment]
It seems I've been having trouble with class hanging around on the classpath from previous runs, restarting jqm has helped clear that - is there another way to deal with that ?

**Comment by simonwibberley** [comment]
I've got it working now. Thanks for the rubberducking!!
