### ISSUE TITLE
Can not launch new job instance on MariaDB 10.4.12 (Column 'INTERNAL_POSITION' cannot be null)

### ISSUE THREAD

**Issue by heikoschwarz** [enioka/jqm#391]
When starting a new job instance I get the following exception (MariaDB 10.4.12):

```
Caused by: com.enioka.jqm.jdbc.DatabaseException: INSERT INTO JQM_JOB_INSTANCE (ID, DATE_ENQUEUE, EMAIL, APPLICATION, KEYWORD1, KEYWORD2, KEYWORD3, MODULE, INTERNAL_POSITION, PARENT, PROGRESS, SESSION_KEY, STATUS, USERNAME, JOBDEF, QUEUE, HIGHLANDER, FROM_SCHEDULE, DATE_NOT_BEFORE, PRIORITY, INSTRUCTION) VALUES(?, CURRENT_TIMESTAMP(3), ?, ?, ?, ?, ?, ?, ROUND(UNIX_TIMESTAMP(CURTIME(4)) * 1000), ?, 0, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    at com.enioka.jqm.jdbc.DbConn.runUpdate(DbConn.java:129)
    at com.enioka.jqm.model.JobInstance.enqueue(JobInstance.java:570)
    at com.enioka.jqm.api.JdbcClient.enqueueWithCnx(JdbcClient.java:329)
    ... 56 more
Caused by: java.sql.SQLIntegrityConstraintViolationException: (conn=123) Column 'INTERNAL_POSITION' cannot be null

```

This error is caused by 'ROUND(UNIX_TIMESTAMP(CURTIME(4))' which returns NULL on that database version. Older versions of MariaDB are working (I've tested it with MariaDb 10.1).

10.4.12-MariaDB-1:10.4.12+maria~bionic:
`select ROUND(UNIX_TIMESTAMP(CURTIME(4)) * 1000);`
returns: NULL

10.1.44-MariaDB-1~bionic:
`select ROUND(UNIX_TIMESTAMP(CURTIME(4)) * 1000);`
returns: 1583578199681

I don't know which MariaDB version causes this breaking change, but the following statement works on the new version:

The following statement works on 10.4.12-MariaDB-1:10.4.12+maria~bionic:
`select ROUND(UNIX_TIMESTAMP(NOW(4)) * 1000);`
returns: 1583578199681

**Comment by echipachenko** [comment]
@marcanpilami

**Comment by marcanpilami** [comment]
`select UNIX_TIMESTAMP(CURTIME(4));` works in 10.3, gives NULL in 10.4. 

`select CURTIME(4);` and `select CURTIME(4)+0;` gives same result in both.

It seems to be the consequence of https://jira.mariadb.org/browse/MDEV-20695 slated for resolution in a future 10.4 release.

We will work around it in the meantime.

**Comment by iherasymenko** [comment]
@marcanpilami thank you for such a short turnaround. Could you please cut a new 2.2.x release with this fix?
